#!/bin/bash

PKG=ocserv
BINDIR=/opt/ocserv/sbin

case "$1" in
    start)
        printf "\nstarting: $PKG"
        $BINDIR/ocserv -c /opt/ocserv/etc/ocserv.conf
        ;;
    stop)
        printf "\nstopping: $PKG"
	killall ocserv-main
        ;;
    *)
        printf "\n\tUsage: $0 < start | stop >\n\n"
        ;;
esac

